# Generated by Django 6.0.1 on 2026-03-24 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('date_of_engagement', models.DateField(max_length=200)),
                ('leave_type', models.CharField(max_length=200)),
                ('leave_entitlement', models.CharField(max_length=200)),
                ('start_date', models.DateField(max_length=200)),
                ('end_date', models.DateField(max_length=200)),
                ('leave_entitlement_granted', models.CharField(blank=True, max_length=200, null=True)),
                ('accrual_per_year', models.CharField(max_length=200)),
                ('leave_start_date', models.DateField(max_length=200)),
                ('leave_end_date', models.DateField(max_length=200)),
                ('number_of_days_taken', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailspermanent')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('name_of_bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailspermanent')),
            ],
        ),
    ]
