# Generated by Django 6.0.1 on 2026-03-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='employee',
        ),
    ]
