# Generated by Django 6.0.1 on 2026-03-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_leavemodel_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='accrual_per_year',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='date_of_engagement',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='leave_end_date',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='leave_entitlement',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='leave_entitlement_granted',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='leave_start_date',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='number_of_days_taken',
        ),
        migrations.RemoveField(
            model_name='leavemodel',
            name='start_date',
        ),
    ]
