# Generated by Django 6.0.1 on 2026-03-24 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetailsContract',
            fields=[
                ('ec_number', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs')], max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('home_address', models.TextField(max_length=100)),
                ('date_of_appointment', models.DateField()),
                ('current_position', models.CharField(max_length=100)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('catchment', models.CharField(choices=[('SAVE', 'SAVE'), ('MANYAME', 'MANYAME'), ('MZINGWANE', 'MZINGWANE'), ('RUNDE', 'RUNDE'), ('MAZOWE', 'MAZOWE'), ('SANYATI', 'SANYATI'), ('GWAYI', 'GWAYI'), ('HEAD OFFICE', 'HEAD OFFICE')], max_length=100)),
                ('grade', models.IntegerField()),
                ('station_cell', models.CharField(blank=True, max_length=100, null=True)),
                ('work_physical_address', models.TextField(blank=True, max_length=100, null=True)),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('drivers_license', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department', models.ManyToManyField(to='employees.departments')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetailsPermanent',
            fields=[
                ('ec_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs')], max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('home_address', models.TextField(max_length=100)),
                ('date_of_appointment', models.DateField()),
                ('current_position', models.CharField(max_length=100)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('catchment', models.CharField(choices=[('SAVE', 'SAVE'), ('MANYAME', 'MANYAME'), ('MZINGWANE', 'MZINGWANE'), ('RUNDE', 'RUNDE'), ('MAZOWE', 'MAZOWE'), ('SANYATI', 'SANYATI'), ('GWAYI', 'GWAYI')], max_length=100)),
                ('grade', models.IntegerField()),
                ('pension_fund', models.CharField(max_length=100)),
                ('station_cell', models.CharField(blank=True, max_length=100, null=True)),
                ('work_physical_address', models.TextField(blank=True, max_length=100, null=True)),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('nssa_number', models.CharField(blank=True, max_length=15, null=True)),
                ('drivers_license', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('department', models.ManyToManyField(to='employees.departments')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenPermanent',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('birth_entry_number', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeedetailspermanent')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleClothingPermanent',
            fields=[
                ('shirt', models.CharField(max_length=10)),
                ('trousers', models.CharField(max_length=10)),
                ('suit', models.CharField(max_length=10)),
                ('jacket', models.CharField(max_length=10)),
                ('jersey', models.CharField(max_length=10)),
                ('tshirt', models.CharField(max_length=10)),
                ('shoes', models.CharField(max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeedetailspermanent')),
            ],
        ),
        migrations.CreateModel(
            name='MaleClothingPermanent',
            fields=[
                ('shirt', models.CharField(max_length=10)),
                ('trousers', models.CharField(max_length=10)),
                ('suit', models.CharField(max_length=10)),
                ('jacket', models.CharField(max_length=10)),
                ('jersey', models.CharField(max_length=10)),
                ('tshirt', models.CharField(max_length=10)),
                ('shoes', models.CharField(max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeedetailspermanent')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKinPermanent',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('relationship', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeedetailspermanent')),
            ],
        ),
        migrations.CreateModel(
            name='SpousesPermanent',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('date_of_marriage', models.DateField(max_length=100)),
                ('cell_number', models.CharField(max_length=100)),
                ('home_address', models.TextField(max_length=100)),
                ('workplace_number', models.CharField(blank=True, max_length=100, null=True)),
                ('workplace_address', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeedetailspermanent')),
            ],
        ),
    ]
