# Generated by Django 6.0.1 on 2026-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailscontract',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employeedetailscontract',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='employeedetailspermanent',
            name='department',
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='ec_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spousespermanent',
            name='id_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='employeedetailspermanent',
            name='department',
            field=models.ManyToManyField(to='employees.departments'),
        ),
    ]
