# Generated by Django 6.0.1 on 2026-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkinpermanent',
            name='contact',
            field=models.IntegerField(default='07722727'),
            preserve_default=False,
        ),
    ]
