# Generated by Django 6.0.1 on 2026-05-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_nextofkinpermanent_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss')], max_length=100),
        ),
    ]
