# Generated by Django 6.0.1 on 2026-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeedetailscontract_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employeedetailscontract',
            name='home_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeedetailscontract',
            name='work_physical_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='home_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='work_physical_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkinpermanent',
            name='relationship',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spousespermanent',
            name='home_address',
            field=models.TextField(max_length=100),
        ),
    ]
