# Generated by Django 6.0.1 on 2026-05-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeedetailspermanent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('COPY_OF_ID', 'Copy of ID'), ('POLICE_CLEARANCE', 'Police Clearance'), ('ACADEMIC', 'Academic Document'), ('OTHER', 'Other')], max_length=50)),
                ('certificate_name', models.CharField(blank=True, max_length=150, null=True)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='employees.employeedetailspermanent')),
            ],
        ),
    ]
