# Generated by Django 6.0.1 on 2026-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_departments_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='department',
            field=models.ManyToManyField(blank=True, to='employees.departments'),
        ),
    ]
