# Generated by Django 6.0.1 on 2026-05-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeedocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDocument',
        ),
    ]
