# Generated by Django 6.0.1 on 2026-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkinpermanent',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nextofkinpermanent',
            name='relationship',
            field=models.CharField(max_length=100),
        ),
    ]
