# Generated by Django 6.0.1 on 2026-05-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_nextofkinpermanent_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetailspermanent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='childrenpermanent',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailspermanent'),
        ),
        migrations.AlterField(
            model_name='femaleclothingpermanent',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailspermanent'),
        ),
        migrations.AlterField(
            model_name='maleclothingpermanent',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailspermanent'),
        ),
        migrations.AlterField(
            model_name='nextofkinpermanent',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailspermanent'),
        ),
        migrations.AlterField(
            model_name='spousespermanent',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailspermanent'),
        ),
    ]
