# Generated by Django 6.0.1 on 2026-06-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='ec_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='ec_number'),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100, verbose_name='gender'),
        ),
    ]
