# Generated by Django 6.0.1 on 2026-05-27 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeedetailspermanent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetailscontract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated'), ('SUSPENDED', 'Suspended'), ('CONTRACT_ENDED', 'Contract Ended')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetailscontract',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Mrs', 'Mrs')], max_length=100),
        ),
        migrations.CreateModel(
            name='ContractEmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('COPY_OF_ID', 'Copy of ID'), ('POLICE_CLEARANCE', 'Police Clearance'), ('ACADEMIC', 'Academic Document'), ('CONTRACT', 'Contract Document'), ('OTHER', 'Other')], max_length=50)),
                ('certificate_name', models.CharField(blank=True, max_length=150, null=True)),
                ('document_file', models.FileField(upload_to='contract_employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_employee_documents', to='employees.employeedetailscontract')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKinContract',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('relationship', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailscontract')),
            ],
        ),
        migrations.CreateModel(
            name='SpousesContract',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('date_of_marriage', models.DateField(max_length=100)),
                ('cell_number', models.CharField(max_length=100)),
                ('home_address', models.TextField(max_length=100)),
                ('workplace_number', models.CharField(blank=True, max_length=100, null=True)),
                ('workplace_address', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeedetailscontract')),
            ],
        ),
    ]
