# Generated by Django 6.0.1 on 2026-06-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeedetailspermanent_ec_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='ec_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeedetailspermanent',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100),
        ),
    ]
