# Generated by Django 6.0.1 on 2026-06-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeedetailscontract_status_and_more'),
        ('employees', '0008_alter_employeedetailspermanent_ec_number_and_more'),
    ]

    operations = [
    ]
