from django.urls import path
from django.contrib import admin
from .import views

urlpatterns = [
    path('permanent-employee-table/', views.EmployeeTablePermanent, name='permanent-employee-table'),
    path('add-permanent-form/', views.addPermanentEmployee, name='add-permanent-form'),
    path('permanent-employee-view/<uuid:pk>/', views.permanentEmployeeView, name='permanent-employee-view'),
    path('edit-permanent-employee/<uuid:pk>/', views.editPermanentEmployee, name='edit-permanent-employee'),
    path('delete-permanent-employee/<uuid:pk>/', views.deletePermanentEmployee, name='delete-permanent-employee'),
    path('spouses-permanent-table/', views.spousePermanentTable, name='spouses-permanent-table'),
    path('add-spouse/', views.addSpouseView, name='add-spouse'),
    path('spouse-view/<str:pk>/' ,views.spouseView, name='spouse-view'),
    path('spouse-edit/<str:pk>/' ,views.editSpouseView , name='spouse-edit'),
    path('delete-spouse/<str:pk>/', views.deleteSpouseView, name='delete-spouse'),
    path('permanent-employee-kin', views.nextOfKinViewTable, name='permanent-employee-kin'),
    path('add-next-of-kin/', views.addNextOfKinView, name='add-next-of-kin'),
    path('permanent-employee-kin-view/<uuid:pk>/', views.nextOfKinView, name='permanent-employee-kin-view'),
    path('edit-next-of-kin/<uuid:pk>/', views.editNextOfKinView, name='edit-next-of-kin'),
    path('delete-next-of-kin/<uuid:pk>/', views.deleteNextOfKinView, name='delete-next-of-kin'),
    path('contract-employee-table/', views.contractEmployeeTable, name='contract-employee-table'),
    path('add-contract-form/', views.addContractEmployee, name='add-contract-form'),
    path('contract-employee-view/<uuid:pk>/', views.contractEmployeeView, name='contract-employee-view'),
    path('edit-contract-employee/<uuid:pk>/', views.editContractEmployee, name='edit-contract-employee'),
    path('delete-contract-employee/<uuid:pk>/', views.deleteContractEmployee, name='delete-contract-employee'),
    path('spouses-contract-table/', views.contractSpouseTable, name='contract-spouses-table'),
    path('add-contract-spouse/', views.addContractSpouseView, name='add-contract-spouse'),
    path('contract-spouse-view/<uuid:pk>/', views.contractSpouseView, name='contract-spouse-view'),
    path('contract-spouse-edit/<uuid:pk>/', views.editContractSpouseView, name='contract-spouse-edit'),
    path('delete-contract-spouse/<uuid:pk>/', views.deleteContractSpouseView, name='delete-contract-spouse'),
    path('contract-employee-kin/', views.contractNextOfKinTable, name='contract-employee-kin'),
    path('add-contract-next-of-kin/', views.addContractNextOfKinView, name='add-contract-next-of-kin'),
    path('contract-employee-kin-view/<uuid:pk>/', views.contractNextOfKinView, name='contract-employee-kin-view'),
    path('edit-contract-next-of-kin/<uuid:pk>/', views.editContractNextOfKinView, name='edit-contract-next-of-kin'),
    path('delete-contract-next-of-kin/<uuid:pk>/', views.deleteContractNextOfKinView, name='delete-contract-next-of-kin'),
]
